pool:
  name: Hosted VS2017
steps:
- task: PowerShell@2
  displayName: Prerequisites
  inputs:
    targetType: filePath
    filePath: './src/build/vsts-prerequisites.ps1'

- task: PowerShell@2
  displayName: Validate
  inputs:
    targetType: filePath
    filePath: './src/build/vsts-validate.ps1'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit

- task: PowerShell@2
  displayName: RegisterRepository
  inputs:
    targetType: filePath
    filePath: './src/build/vsts-registerRepository.ps1'
    arguments:
      -OrganizationName "i-system"
      -RepositoryName "AutomationPlatform"
      -ArtifactFeedName = "AzArtifactsPSModules"
      -ArtifactRepositoryName "IsAzPSRepository"
      -FeedUsername "Ondrej Kracmar"
      -PersonalAccessToken "c3hdrkgv3ealoea5pqsqthmjqh2hynqmmobx3ign5e5mtzehunta"
  condition: always()
  
- task: PowerShell@2
  displayName: Build
  inputs:
    targetType: filePath
    filePath: './src/build/vsts-build.ps1'
    arguments:
      -WorkingDirectory "./src"
      -ApiKey "c3hdrkgv3ealoea5pqsqthmjqh2hynqmmobx3ign5e5mtzehunta"
      -Repository "IsAzPSRepository"

  condition: always()