name: Publish Powershell Module To Private Repository
trigger:
  branches:
    include:
    - main

  paths:
    exclude:
    - CHANGELOG.md

  tags:
    include:
    - "v*"
    exclude:
    - "*-*"

variables:
  - group: "AzArtifactsPSModules"
  - group: "BuildEnvironment"

steps:

   - task: PowerShell@2
     displayName: Calculate Powershell ModuleVersion (GitVersion)
     inputs:
       targetType: inline
       script: |
         dotnet tool install --global GitVersion.Tool
              $gitVersionObject = dotnet-gitversion /config $(sourceDirectory)/GitVersion.yml | ConvertFrom-Json
              $gitVersionObject.PSObject.Properties.ForEach{
                  Write-Host -Object "Setting Task Variable '$($_.Name)' with value '$($_.Value)'."
                  Write-Host -Object "##vso[task.setvariable variable=$($_.Name);]$($_.Value)"
              }
              Write-Host -Object "##vso[build.updatebuildnumber]$($gitVersionObject.FullSemVer)"

   - task: PowerShell@2
     displayName: Install Prerequisites For Validation
     inputs:
       targetType: filePath
       filePath: "$(sourceDirectory)/build/vsts-prerequisites.ps1"

   - task: PowerShell@2
     displayName: Validation/Test Powershell Module
     inputs:
       targetType: filePath
       filePath: "$(sourceDirectory)/build/vsts-validate.ps1"

   - task: PublishTestResults@2
     displayName: "Publish Test Results **/TEST-*.xml"
     inputs:
       testResultsFormat: NUnit
     condition: always()

   - task: PowerShell@2
     displayName: Build Nuget For Powerhell module
     inputs:
       targetType: filePath
       filePath: "$(sourceDirectory)/build/vsts-build.ps1"
       arguments: > # Use this to avoid newline characters in multiline string
          -WorkingDirectory '$(sourceDirectory)'
          -LocalRepo
          -ModuleVersion '$(MajorMinorPatch)'
          -PreRelease '$(NuGetPreReleaseTagV2)'

   - task: PowerShell@2
     displayName: Publish Powershell Module/Nuget To Private Azure Artifact/Powershell Reposityr
     inputs:
        targetType: inline
        script: |
          $source = 'https://pkgs.dev.azure.com/{0}/{1}/_packaging/{2}/nuget/v2' -f '$(company)', '$(project)', '$(feedName)'
          Invoke-Expression "nuget source add -Name '$(feedName)' -Source '$($source)' -username '$(userName)' -password '$(PAT)'"
          $PreRelease = '$(NuGetPreReleaseTagV2)'
          if (-not ([string]::IsNullOrEmpty($PreRelease)))
          {
            Invoke-Expression "nuget push -Source '$(feedName)' -ApiKey ((New-Guid).Guid)  '$(moduleName)$(MajorMinorPatch)-$(NuGetPreReleaseTagV2).nupkg' -SkipDuplicate"
          }
          else
          {
            Invoke-Expression "nuget push -Source '$(feedName)' -ApiKey ((New-Guid).Guid)  '$(moduleName)$(MajorMinorPatch).nupkg' -SkipDuplicate"
          }
