pool:
  name: Hosted VS2017
steps:
- task: PowerShell@2
  displayName: Prerequisites
  inputs:
    targetType: filePath
    filePath: './build/vsts-prerequisites.ps1'

- task: PowerShell@2
  displayName: Validate
  inputs:
    targetType: filePath
    filePath: './build/vsts-validate.ps1'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit
- task: PowerShell@2
  displayName: Build
  inputs:
    targetType: filePath
    filePath: './build/vsts-build.ps1'
    arguments:
        -ApiKey "c3hdrkgv3ealoea5pqsqthmjqh2hynqmmobx3ign5e5mtzehunta"
        -Repository "IsAzPSRepository"
  condition: always()
